// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzudajuvpnliszqikmjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6dWRhanV2cG5saXN6cWlrbWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjY2OTcsImV4cCI6MjA3MTcwMjY5N30.oVaNSM692Jis2FVxSE5oadG2ll0qQ8Je41_L1apH_AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});